# Generated by Django 5.0.6 on 2024-07-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsdetails',
            name='category',
            field=models.CharField(choices=[('NoteBooks', 'NoteBooks'), ('Pens', 'Pens'), ('Pencils', 'Pencils'), ('Dairy', 'Dairy'), ('Tape', 'Tape'), ('Sheets', 'Sheets')], default='NoteBooks', max_length=50),
        ),
    ]
